services:

  api:
    build: 
      context: ./backend
    container_name: url-shortener-backend
    depends_on: [db]
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      SHORT_CODE_LEN: ${SHORT_CODE_LEN}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/

  db:
    image: postgres:16.3
    container_name: url-shortener-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

volumes:
  postgres_data: